name: Build and Publish to jsr

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Extract version from deno.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version deno.json -r"
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'

      - name: Setup Deno2 environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Deno install
        run: deno install --frozen-lockfile
      - name: Lint
        run: deno lint
      - name: Publish to JSR
        run: deno publish
      - name: Build for NPM
        run: deno run -A bin/build-npm.ts
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: ( cd npm && npm publish --access public )
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
